### ISSUE TITLE
Deprecated Keras function ?

### ISSUE THREAD

**Issue by Johnreidsilver** [titu1994/Nested-LSTM#3]
Hi,
I was trying out NestedLSTM over CRAN's R and it seems Keras has removed this function since Keras 2.1.6:
cannot import name '_generate_dropout_ones'

Keras removal of the function:
https://github.com/keras-team/keras/pull/9892

How to interface with NestedLSTM with Rstudio keras library: 
https://github.com/rstudio/keras/issues/610

Thanks

**Comment by titu1994** [comment]
Right. I'll fix that in a bit. Keras layers for recurrent metworks change so often.
